videos-list/12-johns-mmm.md, videos-list/19-brouns.md, videos-list/25-fonnesbeck.md, videos-list/33-wiecki.md, videos-list/README.md
=> add templates for video descriptions

videos-list/03-viola.md
Towards #11 
Closes #13
Add timestamps for video 3: Violeta keynote
=> Add timestamps for video 3: Violeta keynote

videos-list/25-chris.md
References towards #11
Closes #15
Description
Add timestamps for video 25: Chris' keynote
=> Add timestamps for video 25: Chris' keynote

videos-list/27-cameron.md
closes issue #17 
relates to issue #11
in addition: included the link to the slides
=> add timestamps to video 27 cameron cell counting

videos-list/17-ravin.md
Towards #11
Closes #19
Add timestamps for video 17 Ravin Welcome
=> Add timestamps for video 17 Ravin Welcome

videos-list/05-dario-hessam.md
**Reference**
Towards #11 
Closes #21 
**Description**
Add timestamps for video 05:
Speakers: Speaker: Dario Caramelli and Hessam Mehr.
Title: An alcohol? What are the chances! Knowledge-based and probabilistic models in chemistry using PyMC.
Please let me know for any changes, I'll do it asap.
Thanks !
=> add timestamps to 05 Dario-hassam (An alcohol?)

videos-list/04-aki.md
Towards #11
Closes #29
Adjusted auto-timestamps and added new ones
=> Add timestamps for video 04 Aki Vehrati, Inference diagnostics

videos-list/30-quan.md
Towards #11 
Closes #28 
Adds timestamps to video 30 -- Quan Nguyen's talk on Bayesian Machine Learning
cc @AnaRita93 @reshamas 
=> Add timestamps for video 30: Quan on Bayesian ML

videos-list/34-ricardo_aesara.md
=> Video 34: Ricardo talk on pymc, Aesara, Aeppl

videos-list/21-max.md
=> Add timestamps 21 Max Sklar, What is probability?

videos-list/26-ali.md
=> Add timestamps and website of the speaker to the video 26 Ali Akbar, Journey in ML

videos-list/12-michael-zhenyu.md
Toward #11 
Add timestamps for video 12: Michael-Zhenyu Media Mix Modelling
=> Add timestamps for video 12: Michael-Zhenyu Media Mix Modelling

videos-list/07-thomas_part2.md, videos-list/33-thomas_part1.md
Towards #11
Closes #27  
Add timestamps for video 07: Thomas Wiecki Bayesian workflow part 2
cc: @yyyyuans
=> Add timestamps to video 07: Thomas Wiecki part 2

videos-list/28-evdoxia.md
Toward #11 
Closes #41 
Add timestamps for video 28 Evdoxia Taka, Bayesian visualization
=> Add timestamps for video 28 Evdoxia Taka, Bayesian visualization

videos-list/11-mo.md
Towards #11 
Closes #43
Add timestamps for video 11: Novel Bayesian Model to Fit Spectrophotometric Data of Hubble & Spitzer Space Telescopes (Mo Ashkik)
=> Add timestamps for video 11: Novel Bayesian Model to Fit Spectrophotometric Data of Hubble & Spitzer Space Telescopes (Mo Ashkik)

videos-list/10-rob.md
Towards #11 
Closes #46 
Add timestamps to video 10: Rob Zinkov - Model Checking
=> Add timestamps to videos-list/10-rob.md

videos-list/13-pedro-osvaldo.md
Towards #11 
Closes #48 
Add timestamps for video 13: Sequential Monte Carlo: Introduction and Diagnostics (Pedro German Ramirez & Osvaldo Martin)
Part of PyMCon2020
=> Add timestamps for video 13: Sequential Monte Carlo: Introduction and Diagnostics (Pedro German Ramirez & Osvaldo Martin)

videos-list/32-laura-michael.md
Towards #11 
Closes #51 
Adding timestamps for [video 32 : Calibr8: Going Beyond Linear Ranges With Non-Linear Calibration Curves and Multilevel Modeling by Michael Osthege and Laura Helleckes](https://www.youtube.com/watch?v=14Ca--VJKxI) updated in file [32-laura-michael.md](https://github.com/pymc-devs/video-timestamps/blob/main/videos-list/32-laura-michael.md)
#PyMCon 2020
=> Adding timestamps for video 32-laura-michael.md

videos-list/2023/36-danh_gp.md
Issue: #56 
Bio needs to be added, couldn't find the Bio on discourse.
=> Add Dan Phan event

videos-list/2023/35-dante_bayes.md
=> add Dante gates event

videos-list/2023/36-danh_gp.md
Towards #11 
Closes #59 
Add timestamps for video 36: Danh Phan: Gaussian Processes
=> Added timestamps for video 36: Danh Phan: Gaussian Processes
